[package]
name = "c8s"
version = "0.1.0"
description = "A k9s-style TUI for Docker containers"
authors = ["Rob <robertazzopardi@users.noreply.github.com>"]
license = "MIT"
repository = "https://github.com/robertazzopardi/d7s"
edition = "2024"
readme = "README.md"
keywords = [
    "docker",
    "tui",
    "containers",
    "terminal",
]
categories = [
    "command-line-utilities",
    "development-tools",
]

[dependencies]
# Internal
k9tui = { path = "../k9tui", version = "0.1.0" }

# UI
crossterm = { version = "0.29.0", default-features = false, features = ["osc52", "bracketed-paste", "events", "windows"] }
ratatui = { version = "0.30.0", features = ["crossterm"], default-features = false }

# Async
tokio = { version = "1.47.0", features = ["full"] }
futures-util = "0.3"

# Docker
bollard = "0.18"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1.0.142"

# Utilities
color-eyre = "0.6.3"

[lints]
workspace = true
