[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
edition = "2024"
rust-version = "1.88"
authors = ["Rob <robertazzopardi@users.noreply.github.com>"]
license = "MIT"
repository = "https://github.com/robertazzopardi/t7s"

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
strip = true

[workspace.lints.clippy]
indexing_slicing = "deny"
fallible_impl_from = "deny"
wildcard_enum_match_arm = "deny"
unneeded_field_pattern = "deny"
fn_params_excessive_bools = "deny"
must_use_candidate = "deny"
